trad: Acceptance Tests  Do Your Features Work Correctly?
paulojunior-ufla/piramide-de-teste-pratica pull request #25
Opened 2023-11-26 23:26 UTC by luizeduardo7

Foi realizada a tradução da seção 'Acceptance Tests  Do Your Features Work Correctly?' do artigo original.

2023-11-27 19:26 UTC, paulojunior-ufla requested changes
Olá, @luizeduardo7.

Muito obrigado pela colaboração. O trabalho está muito bom e fiz apenas duas solicitações de mudança ao longo do texto.

Aguardo as correções para finalizarmos o processo de merge.

Até mais.
Paulo.

2023-11-28 18:48 UTC, paulojunior-ufla requested changes
Olá, @jonathasluis.

Esse PR é sobre outra seção (Acceptance Tests, do @luizeduardo7). Você pretendem traduzir as duas seções? Caso sim, poderia abrir um novo PR para essa seção de Mocking e Stubbing, por favor?

Até mais.
Paulo.

2023-11-28 19:15 UTC, jonathasluis commented
@paulojunior-ufla pretendemos traduzir as duas seções, por engano ao traduzir a seção Mocking And Stubbing fiz o commit na brench errada. Realizei o Revert e irei abrir um novo PR.

2023-12-01 12:56 UTC, luizeduardo7 commented on README.md
> +Às vezes você ouvirá os termos [**teste funcional**](https://en.wikipedia.org/wiki/Functional_testing) ou [**teste de aceitação**](https://en.wikipedia.org/wiki/Acceptance_testing#Acceptance_testing_
Resolvido

2023-12-01 12:57 UTC, luizeduardo7 reviewed
Feito

2024-01-29 11:00 UTC, merged